/*
 * apfel API
 *
 * [ap]plication [f]or [e]vent [l]ogin
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	Code string `json:"code"`
}
