version: "3.9"

services:
  db:
    image: postgres:11.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=apfel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  web:
    image: vxkfl/apfel
    build: .
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PWD=1234
      - DB_NAME=apfel
      - DB_SSLMODE=disable

volumes:
  db-data:
