/*
 * apfel API
 *
 * [ap]plication [f]or [e]vent [l]ogin
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"apfel/database"
	"log"
	"net/http"
	sw "apfel/go"
)

func main() {
	log.Printf("Connecting to Database...")

	err := database.Connect()
	if err != nil {
		log.Fatal(err)
	}

	defer database.Close()

	log.Printf("Starting server on :8080 ...")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
